name: WebSocket Tests

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}-${{ matrix.version }}
    strategy:
      matrix:
        include:
          - os: ubuntu
            version: 24.04
            gcc: 14
            c_std: 23
            cpp_std: 23

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install dependencies on ubuntu (CC ${{ matrix.gcc }})
        if: matrix.os == 'ubuntu'
        run: |
          sudo apt-get update
          sudo apt-get \
            install -y \
            cmake \
            build-essential \
            gcc-${{ matrix.gcc }} \
            g++-${{ matrix.gcc }} \
            just
          echo "CC=gcc-${{ matrix.gcc }}" >> $GITHUB_ENV
          echo "CXX=g++-${{ matrix.gcc }}" >> $GITHUB_ENV
          echo "C_STD=${{ matrix.c_std }}" >> $GITHUB_ENV
          echo "CPP_STD=${{ matrix.cpp_std }}" >> $GITHUB_ENV

      - name: Build project
        shell: bash
        run: |
          if [ -n "${CC:-}" ]; then
            just debug-build
          fi

      - name: Check link
        if: matrix.os == 'ubuntu'
        shell: bash
        run: |
          echo "Check ldd"
          ldd build/relay
          echo "Check readelf"
          readelf --dyn-syms -W build/relay
